/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blooddonermanagement;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Administrator
 */
public class newDoner extends javax.swing.JFrame {
Connection con=null;
    /**
     * Creates new form search
     */
    public newDoner() {
          initComponents();
        try
        {
           Class.forName("org.sqlite.JDBC"); 
             con=DriverManager.getConnection("jdbc:sqlite:BloodBank.sqlite");
             name.setText("");
         mob.setText("");
         address.setText("");
            state();
        }
        catch(Exception e)
                {
                       JOptionPane.showMessageDialog(null,e);
                }
      
        
    }
    
    public void state()
    {
        state1.removeAllItems();
          try
        {
           Statement stmt = con.createStatement();
         ResultSet res =  stmt.executeQuery("select  distinct(state) from address");
           while(res.next())
           {
               state1.addItem(res.getString(1));
           }
           stmt.close();
        }
        catch(Exception e)
                {  JOptionPane.showMessageDialog(null,e);
                }
        
    }

    
    
     public void dist()
    {
        dist.removeAllItems();
          try
        {
           Statement stmt = con.createStatement();
         ResultSet res =  stmt.executeQuery("select  distinct(dist) from address where state='"+state1.getSelectedItem().toString()+"'");
           while(res.next())
           {
               dist.addItem(res.getString(1));
           }
           stmt.close();
        }
        catch(Exception e)
                { // JOptionPane.showMessageDialog(null,e);
                }
        
    }
     
         public void taluka()
    {
        taluka.removeAllItems();
          try
        {
           Statement stmt = con.createStatement();
         ResultSet res =  stmt.executeQuery("select  distinct(taluka) from address where dist='"+dist.getSelectedItem().toString()+"'");
           while(res.next())
           {
               taluka.addItem(res.getString(1));
           }
           stmt.close();
        }
        catch(Exception e)
                { // JOptionPane.showMessageDialog(null,e);
                }
        
    }
         
         
         
         
           public void insert()
    {
       
          try
        {
           Statement stmt = con.createStatement();
        stmt.executeUpdate("insert into doner values('"+name.getText()+"','"+mob.getText()+"','"+state1.getSelectedItem().toString()+"','"+dist.getSelectedItem().toString()+"','"+taluka.getSelectedItem().toString()+"','"+address.getText()+"','"+group.getSelectedItem().toString()+"')");
        
         JOptionPane.showMessageDialog(null,"DONER ADDED!!");
         name.setText("");
         mob.setText("");
         address.setText("");
           stmt.close();
        }
        catch(Exception e)
                { JOptionPane.showMessageDialog(null,e);
                }
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dist = new javax.swing.JComboBox<>();
        state1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        taluka = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        group = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        mob = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ADD NEW DONER");
        setResizable(false);

        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("SELECT DISTRICT :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 180, 138, 20);

        dist.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dist.setForeground(new java.awt.Color(255, 0, 0));
        dist.setToolTipText("");
        dist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distActionPerformed(evt);
            }
        });
        jPanel2.add(dist);
        dist.setBounds(160, 170, 170, 40);

        state1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        state1.setForeground(new java.awt.Color(255, 0, 0));
        state1.setToolTipText("");
        state1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                state1ActionPerformed(evt);
            }
        });
        jPanel2.add(state1);
        state1.setBounds(160, 120, 170, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("SELECT STATE :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(40, 130, 120, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blooddonermanagement/blood-donation-logo_23-2147506524.jpg"))); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(20, 440, 340, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("SELECT TALUKA:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(30, 230, 130, 20);

        taluka.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        taluka.setForeground(new java.awt.Color(255, 0, 0));
        taluka.setToolTipText("");
        jPanel2.add(taluka);
        taluka.setBounds(160, 220, 170, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("BLOOD GROUP");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 380, 130, 20);

        group.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        group.setForeground(new java.awt.Color(255, 0, 0));
        group.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "B+", "O+", "AB+", "O-", "AB-" }));
        group.setToolTipText("");
        jPanel2.add(group);
        group.setBounds(160, 370, 170, 40);

        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(160, 270, 166, 96);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("ENTER MOBILE :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(40, 70, 120, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setText("ENTER NAME :");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(50, 20, 120, 20);
        jPanel2.add(name);
        name.setBounds(160, 10, 170, 40);
        jPanel2.add(mob);
        mob.setBounds(160, 60, 170, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("ENTER ADDRESS :");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 300, 130, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blooddonermanagement/back - Copy.jpg"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(-20, -20, 400, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if("".equals(name.getText()) ||"".equals(mob.getText()))
        {
            JOptionPane.showMessageDialog(null,"Enter all details");
        }
        else
        {
            insert();
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void state1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_state1ActionPerformed
        // TODO add your handling code here:
        dist();
    }//GEN-LAST:event_state1ActionPerformed

    private void distActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distActionPerformed
        // TODO add your handling code here:
        taluka();
    }//GEN-LAST:event_distActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newDoner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newDoner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newDoner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newDoner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newDoner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JComboBox<String> dist;
    private javax.swing.JComboBox<String> group;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mob;
    private javax.swing.JTextField name;
    private javax.swing.JComboBox<String> state1;
    private javax.swing.JComboBox<String> taluka;
    // End of variables declaration//GEN-END:variables
}
