/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blooddonermanagement;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Administrator
 */
public class search extends javax.swing.JFrame {
Connection con=null;
    /**
     * Creates new form search
     */
    public search() {
       initComponents();
         
        try
        {
           Class.forName("org.sqlite.JDBC"); 
             con=DriverManager.getConnection("jdbc:sqlite:BloodBank.sqlite");
            
           state();
           name.setActionCommand("");
           mob.setActionCommand("");
           jPanel1.setVisible(false);
           reqButton.setVisible(false);
        }
        catch(Exception e)
                {
                       JOptionPane.showMessageDialog(null,e);
                }
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dist = new javax.swing.JComboBox<>();
        state1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        reqButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        taluka = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        group = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mob = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("SELECT DISTRICT :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 90, 138, 20);

        dist.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dist.setForeground(new java.awt.Color(255, 0, 0));
        dist.setToolTipText("");
        dist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distActionPerformed(evt);
            }
        });
        jPanel2.add(dist);
        dist.setBounds(160, 80, 170, 40);

        state1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        state1.setForeground(new java.awt.Color(255, 0, 0));
        state1.setToolTipText("");
        state1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                state1ActionPerformed(evt);
            }
        });
        jPanel2.add(state1);
        state1.setBounds(160, 30, 170, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("SELECT STATE :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(40, 40, 120, 20);

        reqButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reqButton.setText("SEND REQUEST SMS");
        reqButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqButtonActionPerformed(evt);
            }
        });
        jPanel2.add(reqButton);
        reqButton.setBounds(400, 260, 230, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("SELECT TALUKA:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(30, 140, 130, 20);

        taluka.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        taluka.setForeground(new java.awt.Color(255, 0, 0));
        taluka.setToolTipText("");
        jPanel2.add(taluka);
        taluka.setBounds(160, 130, 170, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("BLOOD GROUP");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 190, 130, 20);

        group.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        group.setForeground(new java.awt.Color(255, 0, 0));
        group.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "B+", "O+", "AB+", "O-", "AB-" }));
        group.setToolTipText("");
        jPanel2.add(group);
        group.setBounds(160, 180, 170, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "MOBILE NUMBER", "ADDRESS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(350, 10, 330, 230);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ENTER YOUR CONTACT DETAILS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N

        jLabel1.setText("NAME :");

        jLabel2.setText("MOBILE :");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blooddonermanagement/pack08-21-512.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mob, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(mob, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(30, 320, 630, 130);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blooddonermanagement/logo1.png"))); // NOI18N
        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(100, 260, 190, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blooddonermanagement/back - Copy.jpg"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(-20, -20, 700, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
     public void state()
    {
        state1.removeAllItems();
          try
        {
           Statement stmt = con.createStatement();
         ResultSet res =  stmt.executeQuery("select  distinct(state) from address");
           while(res.next())
           {
               state1.addItem(res.getString(1));
           }
           stmt.close();
        }
        catch(Exception e)
                {  JOptionPane.showMessageDialog(null,e);
                }
        
    }
     
     
     
     public void dist()
    {
        dist.removeAllItems();
          try
        {
           Statement stmt = con.createStatement();
         ResultSet res =  stmt.executeQuery("select  distinct(dist) from address where state='"+state1.getSelectedItem().toString()+"'");
           while(res.next())
           {
               dist.addItem(res.getString(1));
           }
           stmt.close();
        }
        catch(Exception e)
                { // JOptionPane.showMessageDialog(null,e);
                }
        
    }
     
     
     public void taluka()
    {
        taluka.removeAllItems();
          try
        {
           Statement stmt = con.createStatement();
         ResultSet res =  stmt.executeQuery("select  distinct(taluka) from address where dist='"+dist.getSelectedItem().toString()+"'");
           while(res.next())
           {
               taluka.addItem(res.getString(1));
           }
           stmt.close();
        }
        catch(Exception e)
                { // JOptionPane.showMessageDialog(null,e);
                }
        
    }
     
     
      public void showrecord()
    {
        
        
         DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
         while(model.getRowCount()>0)
         {
             model.removeRow(0);
         }
        
        try
        {
           
             Statement stmt1=con.createStatement();
        ResultSet res1=stmt1.executeQuery("select name,mob,address from doner where taluka='"+taluka.getSelectedItem().toString()+"' AND blood='"+group.getSelectedItem().toString()+"'");
     
       if(res1.next())
       {
            Statement stmt=con.createStatement();
        ResultSet res=stmt.executeQuery("select name,mob,address from doner where taluka='"+taluka.getSelectedItem().toString()+"' AND blood='"+group.getSelectedItem().toString()+"'");
       
      
       
        while(res.next()){
        
                   
                    model.addRow(new Object[]{res.getString(1),res.getLong(2),res.getString(3)});
            
        }
          stmt1.close();
        stmt.close();
        reqButton.setVisible(true);
       
       }
       else
       {
           JOptionPane.showMessageDialog(null, "No doner found in your selected area!!");
             jPanel1.setVisible(false);
           reqButton.setVisible(false);
       }
            
       
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
         
      
      
      
      

    
    private void reqButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqButtonActionPerformed
        // TODO add your handling code here:
       jPanel1.setVisible(true);
    }//GEN-LAST:event_reqButtonActionPerformed

    private void distActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distActionPerformed
        // TODO add your handling code here:
        taluka();
    }//GEN-LAST:event_distActionPerformed

    private void state1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_state1ActionPerformed
        // TODO add your handling code here:
        dist();
    }//GEN-LAST:event_state1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        showrecord();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if("".equals(name.getText()) || "".equals(mob.getText()))
        {
             JOptionPane.showMessageDialog(null, "enter all details first!!");
        }
        else
        {
             try
        {
         DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
         sms s=new sms();
          for(int i=0 ;i<jTable1.getRowCount();i++)
       {
           
         String distAddress=jTable1.getValueAt(i, 1)+"";
         s.sendsms(mob.getText(), name.getText(), distAddress);
         
       }
            JOptionPane.showMessageDialog(null, "REQUEST SENDED SUCCESS");
            jPanel1.setVisible(false);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> dist;
    private javax.swing.JComboBox<String> group;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField mob;
    private javax.swing.JTextField name;
    private javax.swing.JButton reqButton;
    private javax.swing.JComboBox<String> state1;
    private javax.swing.JComboBox<String> taluka;
    // End of variables declaration//GEN-END:variables
}
